### PR TITLE
"InstanceIds" sent as array

### PR DESCRIPTION
**Pull request by Yanivro**
Added square brackets to the value of "InstanceIds"

### CODE REVIEW

**Comment by gbowerman** [comment]
@Yanivro thanks for looking at this. These functions are designed to be called with a string dump of a list, e.g.:
current_vmss.upgradevm(json.dumps(batch_list))  
Example taken from [https://github.com/gbowerman/vmssdashboard/blob/master/vmsseditor.py](https://github.com/gbowerman/vmssdashboard/blob/master/vmsseditor.py).
If you're working with a list it's easier to do this than remove the brackets. Can you look into calling it that way and see if it works for you? Other options would be to change these functions to take a Python list instead of a string and do the json.dumps() inside the functions.

**Comment by Yanivro** [comment]
@gbowerman It's only works for me if I pass it with brackets("[1,2,5]")

**Comment by gbowerman** [comment]
@Yanivro if you have a Python list, e.g. my_list = [1,2,3]
You can pass it directly into the function call with:
import json
instance_ids_str = json.dumps(my_list)

That's why the function is designed to accept a string with brackets - it's a string dump of a Python list, so very easy to dump a Python list of VM id's into the function.

**Comment by gbowerman** [comment]
Closing for now. The input should be a Python list, or a string representation of a Python list (which it is now).

**Pull request closed without merging**
