### PR TITLE
Added listing security and application groups

### PR DESCRIPTION
**Pull request by mfunger**
to networkrp.py. Both for a subscription and a resource group.

This is my first open-source PR!

### CODE REVIEW

**Comment by gbowerman** [comment]
@mfunger - added tests and fixed a couple of issues with this checkin: https://github.com/gbowerman/azurerm/commit/e1457f0030e1fe98ebaa7a77a4706ee6fb3b919c

**Comment by gbowerman** [comment]
@mfunger new Pypi version 0.9.17 - please test your fns work correctly https://pypi.org/project/azurerm/ - thanks

**Comment by mfunger** [comment]
@gbowerman they look good to me.

**Comment by gbowerman** [comment]
Thanks again to contributing to azurerm!

**Pull request merged**
