### PR TITLE
service principal added for acs provisioning k8s

### PR DESCRIPTION
**Pull request by pothedar**
kubernetes orchestration was broken because a valid service principal object was missing.

### CODE REVIEW

**Comment by gbowerman** [comment]
@pothedar thanks for addressing this. One question, why did you add extra fields to azurermconfig.json.tmpl? Why not use the existing appId and appSecret properties?

**Comment by pothedar** [comment]
@gbowerman sorry, i totally missed that. Fixed that, updated Read Me and the test as well.

**Comment by gbowerman** [comment]
@pothedar do app_id, app_secret have any purpose if you're creating acs with another orchestrator like DCOS? If not, it may be better if they are optional parameters at the end, e.g.
def create_container_service(access_token, subscription_id, resource_group, service_name, \
    agent_count, agent_vm_size, agent_dns, master_dns, admin_user, public_key, location, \
    master_count=3, orchestrator='DCOS', app_id=None, app_secret=None):
....
if app_secret is not None:
    sp_profile['Secret'] = app_secret
etc..

what do you think?

**Comment by pothedar** [comment]
@gbowerman agreed.

**Comment by gbowerman** [comment]
azurerm-0.7.24 uploaded to pypi. Thanks @pothedar

**Pull request merged**
