### PR TITLE
Add ability to list deployment operations

### PR DESCRIPTION
**Pull request by rcarmo**
Just what it says in the subject, really. Will be doing a few more of these for completeness as I tackle a little challenge I have.

### CODE REVIEW

**Comment by gbowerman** [comment]
Can you also add updates to the following to the pull request:
https://github.com/gbowerman/azurerm/blob/master/azurerm/__init__.py and https://github.com/gbowerman/azurerm/blob/master/README.md

Have you tested it? I don't think it will work until you update __init__.py

Thanks
Guy

**Comment by rcarmo** [comment]
Oh, I wrote the function separately and tested it as part of my "azurerm_utils" module. I'll do those changes, sure.

**Comment by rcarmo** [comment]
There, this ought to do it. Apologies for the merges, I'm on my iPad now instead of my Mac.

**Comment by gbowerman** [comment]
@rcarmo Looks good. I'll merge and push a new version to pypi. 
Thanks for contributing to azurerm.

**Comment by rcarmo** [comment]
I might be doing a few more in the coming days - I have a need for introspecting deployment results and suchlike, and `azurerm` is so simple to extend that there's really no contest :)

**Comment by gbowerman** [comment]
Thanks, will look forward to any additions. In the meantime your changes have been built and uploaded to https://pypi.python.org/pypi/azurerm

**Pull request merged**
